apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-b
  name: service-b
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: deployment-b
  type: ClusterIP