apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-c
  name: service-c
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: deployment-c
  type: ClusterIP