apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-a
  name: service-a
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: deployment-a
  type: NodePort
